spring:
  application:
    name: enternal-rune-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/PhoneDB
    username: postgres
    password: postgrespassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

qr:
  acc: 0889323138
  bank: VPBank
  template: qronly
  download: true

payment:
  api_key: j4fLfGVWhgSK0AUG1nm2YqsZ57wQwWRfPEY4GGXa9vMDe+xThVgXVYYz/Nv1oLuhoaKF+COdx35bNJKhWL89C0kBo8s=

server:
  port: 8080