export enum ShippingStatus {
    PENDING = "PENDING",
    PROCESSING = "PROCESSING",
    SHIPPED = "SHIPPED",
    IN_TRANSIT = "IN_TRANSIT",
    DELIVERED = "DELIVERED",
    FAILED_DELIVERY = "FAILED_DELIVERY",
    RETURNED = "RETURNED",
    CANCELLED = "CANCELLED"
}