export const colors = {
    BAC: { name: 'Bạc', hex: '#C0C0C0' },
    XANH: { name: 'Xanh', hex: '#008000' },
    DEN: { name: 'Đen', hex: '#000000' },
    XANH_DUONG: { name: 'Xanh dương', hex: '#0000FF' },
    XANH_LA: { name: 'Xanh lá', hex: '#00FF00' },
    VANG: { name: 'Vàng', hex: '#FFFF00' },
    TIM: { name: 'Tím', hex: '#800080' },
    CAM: { name: 'Cam', hex: '#FFA500' },
    HONG: { name: 'Hồng', hex: '#FFC0CB' },
    TRANG: { name: 'Trắng', hex: '#FFFFFF' },
    XAM: { name: 'Xám', hex: '#808080' },
    DO: { name: 'Đỏ', hex: '#FF0000' },
    DONG: { name: 'Đồng', hex: '#B87333' },
    XANH_NHAT: { name: 'Xanh nhạt', hex: '#ADD8E6' },
    XANH_LUC_BAO: { name: 'Xanh lục bảo', hex: '#006A4E' },
    TIM_BAC: { name: 'Tím bạc', hex: '#D8BFD8' },
    DEN_HUYEN: { name: 'Đen huyền', hex: '#0A0A0A' },
    XANH_NAVY: { name: 'Xanh navy', hex: '#000080' },
    DEN_TITAN: { name: 'Đen titan', hex: '#1C1C1C' },
    XAM_KHOI: { name: 'Xám khói', hex: '#B0B0B0' },
    XANH_DA_TROI: { name: 'Xanh da trời', hex: '#87CEEB' },
    XAM_BAC: { name: 'Xám bạc', hex: '#C0C0C0' },
    KEM: { name: 'Kem', hex: '#F5F5DC' },
    TRANG_BAC: { name: 'Trắng/bạc', hex: '#F8F8FF' },
    XANH_DUONG_NHAT: { name: 'Xanh dương nhạt', hex: '#ADD8E6' },
};
